### ISSUE TITLE
draggable

### ISSUE THREAD

**Issue by 2qq2qq** [slutske22/leaflet-popup-modifier#4]
set draggable: true,
but the markerPosition not  update after  draggable
help me  
thanks

**Comment by slutske22** [comment]
I'm not 100% sure what you're asking.  Can you explain a bit more, or show me the code that's having a problem?

**Comment by 2qq2qq** [comment]
The setting mark can be dragged, but after dragging, the longitude and latitude of the pop are not updated. 

How can I display multiple popups at the same time? Click anywhere and popups will disappear. I hope only click x to close.

**Comment by slutske22** [comment]
These are not issues with leaflet-popup-modifier, so much as general questions about leaflet popups.  Without seeing your code, I can't diagnose exactly what is going wrong, so perhaps this is better discussed as a question on stack overflow.  However, I can give you some general guidance:

If you are setting a popup on a marker, and the popup of that marker contains the marker's `latLng` information, that popup content is set at the time that the popup is created.  Just because the marker is dragged, it does not mean that the popup content will change.  If you want to update the popup content to match the `latLng` of the marker after the drag is done, you need to tap into the [`dragend`](https://leafletjs.com/reference-1.7.1.html#dragendevent) event of the marker.  Something like this:

```javascript
const yourLatLng = { lat: 22, lng: 45 };
const marker = L.marker(yourLatLng)
marker.bindPopup(`Location of this marker is ${yourLatLng.lat} ${yourLatLng.lng}`);
marker.addTo(map);

marker.on('dragend', e => {
  const newLatLng = e.target.getLatLng(); // <-------- get the new latlng of the marker when the drag is over
  marker.getPopup().setContent(`Location of this marker is ${newLatLng.lat} ${newLatLng.lng}`);
})
```

Or something to that effect.  Note I have not tested this code so you'll have to play aroud with it and make any necessary changes.

As far as keeping multple popups open at the same time you can use the [autoClose](https://leafletjs.com/reference-1.7.1.html#popup-autoclose) option on a popup to prevent it from closing when the user clicks elsewhere on the map.
